### PR TITLE
Create .pullapprove.yml

### PR DESCRIPTION
**Pull request by gdemarcsek**
added pullapprove for test

### CODE REVIEW

**Comment by kepten** [comment]
Approve

**Comment by kepten** [comment]
Approve for the second time

**Comment by kepten** [comment]
Approved

**Comment by gdemarcsek** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/gdemarcsek/dotfiles/pull-request/1/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=gdemarcsek/dotfiles)

**Pull request merged**
